POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de JavaScript avançado 2321"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/12a5a44a-8679-4d71-849d-2aea0ca6ed86
